
server:
   port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:8080/realms/university
jwt:
  auth:
    converter:
      resource-id: course-management
      principal-attribute: preferred_username
